# Generated by Django 4.0.3 on 2022-03-09 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
