# Generated by Django 4.0.3 on 2022-03-09 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='chatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrelationship', to_field='chatID'),
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
