# Generated by Django 4.0.3 on 2022-03-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_testdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDB',
        ),
    ]
