# Generated by Django 4.0.3 on 2022-03-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_testdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontent',
            old_name='data',
            new_name='date',
        ),
    ]
