# Generated by Django 4.0.3 on 2022-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_data_chatcontent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='status',
            field=models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image'), ('FILE', 'file')], default='TEXT', max_length=10),
        ),
    ]
