# Generated by Django 4.0.3 on 2022-03-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatcontent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontent',
            old_name='content',
            new_name='massage',
        ),
    ]
