# Generated by Django 4.0.3 on 2022-03-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_content_chatcontent_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontent',
            old_name='massage',
            new_name='message',
        ),
    ]
