# Generated by Django 4.0.3 on 2022-03-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_massage_chatcontent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
